import { staticFile } from "remotion";

export const data = [
  {
    topTitle: "Batman",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Batarangs & Batmobile",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Wonder Woman",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Lasso of Truth, Sword of Athena & Bracelets of Submission",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Green Lantern",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Power Ring",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Aquaman",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Trident of Poseidon",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Deathstroke",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "God Killer Sword",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Harley Quinn",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Baseball Bat & Mallet",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Green Arrow",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Trick Arrows",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Catwoman",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Bullwhip",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Nightwing",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Escrima Sticks",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Red Hood",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Dual Guns",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Hawkman",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Nth Metal Mace",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Hawkgirl",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Nth Metal Mace",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Batgirl",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Batarangs",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Robin",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Katana",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Ra's Al Ghul",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Sword",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Rorschach",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Grappling Gun",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Joker",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Smilex",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Blue Beetle",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "The Scarab",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Peacemaker",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Colt Single Action Army",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Superman",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Himself",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Captain Boomerang",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Boomerangs",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Lex Luthor",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Kryptonite",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Two-Face",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Dual Pistols",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Dr. Fate",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Helmet of Fate",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "The Penguin",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Umbrella Gun",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Booster Gold",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Energy Blasters",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Mr. Freeze",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Freeze Gun",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Deadshot",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Ar-15 Sniper Rifle",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Black Manta",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Laser-eye helmet",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Huntress",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Crossbow",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Steel",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Sledgehammer",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Katana",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Soultaker sword",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Black Canary",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Bo Staff",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Azrael",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Flame Sword",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Arsenal",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Prosthetic arm",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Vixen",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Tantu Totem",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
  {
    topTitle: "Bronze Tiger",
    topImageSrc: staticFile("comic/dc/Batman.jpg"),
    bottomTitle: "Claw gauntlets",
    bottomImageSrc: staticFile("comic/dc/Batman.jpg"),
  },
];
