import { staticFile } from "remotion";

export const data = [
  {
    title: "Iron Man",
    description: "Avengers #1 (Sep 1963)",
    subTitle: "Tony Stark",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Thor",
    subTitle: "Thor Odinson",
    description: "Avengers #1 (Sep 1963)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Hulk",
    subTitle: "Dr. Robert Bruce Banner",
    description: "Avengers #1 (Sep 1963)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Wasp",
    subTitle: "Janet van Dyne",
    description: "Avengers #1 (Sep 1963)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ant-Man",
    subTitle: 'Dr. Henry "Hank" Pym',
    description: "Avengers #1 (Sep 1963)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Captain America",
    subTitle: "Steve Rogers",
    description: "Avengers #4 (Mar 1964)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Hawkeye",
    subTitle: "Clint Barton",
    description: "Avengers #16 (May 1965)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Quicksilver",
    subTitle: "Pietro Maximoff",
    description: "Avengers #16 (May 1965)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Scarlet Witch",
    subTitle: "Wanda Maximoff",
    description: "Avengers #16 (May 1965)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Swordsman",
    subTitle: "Jacques Duquesne",
    description: "Avengers #20 (Sep 1965)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Hercules",
    subTitle: "Heracles",
    description: "Avengers #45 (Oct 1967)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Black Panther",
    subTitle: "T'Challa",
    description: "Avengers #52 (May 1968)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Vision",
    description: "Avengers #58 (Nov 1968)",
    subTitle: "Victor Shade",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Black Knight",
    subTitle: "Dane Whitman",
    description: "Avengers #71 (Dec 1969)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Black Widow",
    subTitle: "Natalia Romanova",
    description: "Avengers #111 (May 1973)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Mantis",
    subTitle: "Brandt",
    description: "Avengers #114 (Aug 1973)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Two-Gun Kid",
    subTitle: "Matthew Hawk/Liebowitz",
    description: "Avengers #142 (Dec 1975)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Hellcat",
    subTitle: "Patsy Walker",
    description: "Avengers #151 (Sep 1976)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Beast",
    subTitle: 'Dr. Henry "Hank" McCoy',
    description: "Avengers #151 (Sep 1976)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Moondragon",
    subTitle: "Heather Douglas",
    description: "Avengers #151 (Sep 1976)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Wonder Man",
    subTitle: "Simon Williams",
    description: "Avengers #158 (Apr 1977)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ms. Marvel / Captain Marvel",
    subTitle: "Carol Danvers",
    description: "Avengers #183 (May 1979)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Falcon",
    subTitle: "Sam Wilson",
    description: "Avengers #184 (Jun 1979)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Tigra",
    subTitle: "Greer Grant Nelson",
    description: "Avengers #211 (Sep 1981)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "She Hulk",
    description: "Avengers #221 (Jul 1982)",
    subTitle: "Jennifer Walters",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Captain Marvel / Spectrum",
    subTitle: "Monica Rambeau",
    description: "Avengers #231 (May 1983)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Starfox",
    subTitle: "Eros",
    description: "Avengers #243 (May 1984)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Mockingbird",
    subTitle: "Barbara Morse",
    description: "West Coast Avengers #1 (Sep 1984)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "War Machine",
    subTitle: 'James "Rhodey" Rhodes',
    description: "West Coast Avengers #1 (Sep 1984)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Namor",
    subTitle: "Namor McKenzie",
    description: "Avengers #262 (Dec 1985)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Thing",
    subTitle: "Ben Grimm",
    description: "West Coast Avengers V2 #9 (Jun 1986)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Doctor Druid",
    subTitle: "Dr. Anthony Ludgate Druid",
    description: "Avengers #278 (Apr 1987)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Firebird / La Espirita",
    subTitle: "Bonita Juarez",
    description: "West Coast Avengers V2 #24 (Sep 1987)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Moon Knight",
    subTitle: "Marc Spector",
    description: "West Coast Avengers V2 #33 (Jun 1988)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Demolition Man",
    subTitle: "Dennis Dunphy",
    description: "Captain America #349 (Jan 1989)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Mr. Fantastic",
    subTitle: "Reed Richards",
    description: "Avengers #300 (Feb 1989)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "The Invisible Woman",
    description: "Avengers #300 (Feb 1989)",
    subTitle: "Sue Storm-Richards",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Forgotten One",
    subTitle: "Unknown",
    description: "Avengers #300 (Feb 1989)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "U.S. Agent",
    subTitle: "John Walker",
    description: "West Coast Avengers V2 #44 (May 1989)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Quasar",
    subTitle: "Wendell Vaughn",
    description: "Avengers Annual #18 (Oct 1989)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Human Torch",
    subTitle: "Jim Hammond",
    description: "Avengers: West Coast #50 (Nov 1989)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Sersi",
    subTitle: "Sersi",
    description: "Avengers #314 (Feb 1990)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Spider Man",
    subTitle: "Peter Parker",
    description: "Avengers #316 (Apr 1990)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Stingray",
    subTitle: "Walter Newell",
    description: "Circa Avengers #319 (Jul 1990)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Rage",
    subTitle: "Elvin Haliday",
    description: "Avengers #329 (Feb 1991)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Sandman",
    subTitle: "William Baker/Flint Marko",
    description: "Avengers #329 (Fub 1991)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Machine Man",
    subTitle: "X-51 / Aaron Stack",
    description: "Avengers: West Coast #69 (Apr 1991)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Living Lightning",
    subTitle: "Miguel Santos",
    description: "Avengers: West Coast #74 (Sep 1991)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Spider Woman",
    subTitle: "Julia Carpenter",
    description: "Avengers: West Coast #74 (Sep 1991)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Thunderstrike",
    subTitle: "Eric Masterson",
    description: "Avengers #343 (Jan 1992)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Crystal",
    subTitle: "Crystalia Amaquelin",
    description: "Avengers #343 (Jan 1992)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Darkhawk",
    subTitle: "Chris Powell",
    description: "Avengers: West Coast #94 (May 1993)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Firestar",
    subTitle: "Angelica Jones",
    description: "Avengers V3 #7 (Aug 1998)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Justice",
    subTitle: "Vance Astrovik",
    description: "Avengers V3 #7 (Aug 1998)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Triathlon / 3-D Man",
    subTitle: "Delroy Garrett, Jr.",
    description: "Avengers V3 #27 (Apr 2000)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Silverclaw",
    subTitle: "Maria de Guadalupe Santiago",
    description: "Avengers V3 #30 (Jul 2000)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Jack of Hearts",
    subTitle: "Jack Hart",
    description: "Avengers V3 #43 (Aug 2001)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ant-Man",
    description: "Avengers V3 #62 (Feb 2003)",
    subTitle: "Scott Lang",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Lionheart",
    subTitle: "Kelsey Leigh",
    description: "Avengers V3 #81 (Jun 2004)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Luke Cage",
    subTitle: "Luke Cage/Carl Lucas",
    description: "New Avengers #3 (Mar 2005)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Wolverine",
    subTitle: 'James "Logan" Howlett',
    description: "New Avengers #6 (Jun 2005)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  // {
  //   title: "Young Avengers",
  //   subTitle: "Iron Lad, Hulkling, Namorita, Stature, Wonder Man",
  //   description: "Young Avengers #1 (Apr 2005)",
  //   imageSrc: staticFile("marvel/Iron man.jpg"),
  // },
  {
    title: "Sentry",
    subTitle: "Robert Reynolds",
    description: "New Avengers #10 (Oct 2005)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ronin / Echo",
    subTitle: "Maya Lopez",
    description: "New Avengers #11 (Nov 2005)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Doctor Strange",
    subTitle: "Dr. Stephen Strange",
    description: "New Avengers #27 (Apr 2007)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Iron Fist",
    subTitle: "Danny Rand",
    description: "New Avengers #27 (Apr 2007)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ares",
    subTitle: "Ares",
    description: "Mighty Avengers #1 (May 2007)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Winter Soldier",
    subTitle: 'James Buchanan "Bucky" Barnes',
    description: "New Avengers #48 (Feb 2009)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Spider-Woman",
    subTitle: "Jessica Drew",
    description: "New Avengers #48 (Feb 2009)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Amadeus Cho",
    description: "Mighty Avengers #21 (Mar 2009)",
    subTitle: "Amadeus Cho",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Jocasta",
    subTitle: "Jocasta",
    description: "Mighty Avengers #21 (Mar 2009)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Stature",
    subTitle: "Cassandra Lang",
    description: "Mighty Avengers #22 (Apr 2009)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Black Ant",
    subTitle: "Eric O'Grady",
    description: "Secret Avengers #1 (May 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Valkyrie",
    subTitle: "Brunhilde",
    description: "Secret Avengers #1 (Jul 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ant-Man",
    subTitle: "Eric O'Grady",
    description: "Secret Avengers #1 (Jul 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Nova",
    subTitle: "Richard Rider",
    description: "Secret Avengers #1 (Jul 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Agent 13",
    subTitle: "Sharon Carter",
    description: "Secret Avengers #1 (Jul 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Captain Britain",
    subTitle: "Brian Braddock",
    description: "Age of Heroes #1 (Jul 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Power Woman",
    subTitle: "Jessica Jones",
    description: "New Avengers V2 #1 (Aug 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Protector / Marvel Boy",
    subTitle: "Noh-Varr",
    description: "Avengers V4 #6 (Dec 2010)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Red Hulk",
    subTitle: 'Thaddeus "Thunderbolt" Ross',
    description: "Avengers V4 #12 (Jun 2011)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Daredevil",
    subTitle: "Matt Murdock",
    description: "New Avengers V2 #16 (Nov 2011)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Storm",
    subTitle: "Ororo Monroe",
    description: "Avengers V4 #19 (Jan 2012)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Quake",
    description: "Avengers V4 #19 (Jan 2012)",
    subTitle: "Daisy Johnson",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Agent Venom",
    subTitle: 'Eugene "Flash" Thompson',
    description: "Secret Avengers #23 (Apr 2012)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Havok",
    subTitle: "Alex Summers",
    description: "Uncanny Avengers #1 (Dec 2012)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Sunspot",
    subTitle: "Roberto da Costa",
    description: "Avengers V5 #1 (Feb 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Cannonball",
    subTitle: "Sam Guthrie",
    description: "Avengers V5 #1 (Feb 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Manifold",
    subTitle: "Eden Fesi",
    description: "Avengers V5 #1 (Feb 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Shang-Chi",
    subTitle: "Shang-Chi",
    description: "Avengers V5 #1 (Feb 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Captain Universe",
    subTitle: "Tamara Devoux",
    description: "Avengers V5 #1 (Feb 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Smasher",
    subTitle: "Izzy Kane",
    description: "Avengers V5 #1 (Feb 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Hyperion",
    subTitle: "Marcus Milton",
    description: "Avengers V5 #1 (Feb 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Superior Spider-Man",
    subTitle: "Otto Octavius/Peter Parker",
    description: "Circa Avengers V5 #6 (Apr 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Rogue",
    subTitle: "Anna Marie",
    description: "Uncanny Avengers #4 (Apr 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Sunfire",
    subTitle: "Shiro Yashida",
    description: "Uncanny Avengers #5 (May 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Avengers A.I.",
    subTitle: "Hank Pym, Vision, Doombot, Victor Mancha, Agent Monica Chang",
    description: "Avengers A.I. #1 (Sep 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Star Brand",
    subTitle: "Kevin Connor",
    description: "Avengers V5 #17 (Oct 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Nightmask",
    subTitle: "Adam",
    description: "Avengers V5 #17 (Oct 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Abyss",
    subTitle: "Abyss",
    description: "Avengers V5 #17 (Oct 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ex Nihilo",
    subTitle: "Ex Nihilo",
    description: "Avengers V5 #17 (Oct 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Blade",
    subTitle: "Eric Brooks",
    description: "Mighty Avengers V2 #1 (Nov 2013)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Power Man",
    subTitle: "Victor Alvarez",
    description: "Mighty Avengers V2 #3 (Jan 2014)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Blue Marvel",
    subTitle: "Adam Brashear",
    description: "Mighty Avengers V2 #3 (Jan 2014)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "White Tiger",
    description: "Mighty Avengers V2 #3 (Jan 2014)",
    subTitle: "Ava Ayala",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Alexis the Protector",
    subTitle: "Alexis",
    description: "Avengers A.I #3 (Sep 2014)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Kaluu",
    subTitle: "Kaluu",
    description: "Captain America and the Mighty Avengers #2 (Jan 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Doctor Voodoo",
    subTitle: "Jericho Drumm",
    description: "Avengers & X-Men: Axis #9 (Feb 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Nova",
    subTitle: "Sam Alexander",
    description: "Nova V5 #25 (Feb 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Validator",
    subTitle: "Michaud",
    description: "Circa Avengers V5 #39 (Feb 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Pod",
    subTitle: "Aikku Jokinen",
    description: "Circa Avengers V5 #39 (Feb 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Children of the Sun",
    subTitle: "N/A",
    description: "Circa Avengers V5 #39 (Feb 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Valkyrie",
    subTitle: "Jane Foster",
    description: "All-New All-Different Avengers #1 (May 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ms. Marvel",
    subTitle: "Kamala Khan",
    description: "All-New All-Different Avengers #1 (May 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Spider-Man",
    subTitle: "Miles Morales",
    description: "All-New All-Different Avengers #1 (May 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Deadpool",
    subTitle: "Wade Wilson",
    description: "Avengers #0 (Oct 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Synapse",
    subTitle: "Emily Guerrero",
    description: "Avengers #0 (Oct 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Human Torch",
    subTitle: "Johnny Storm",
    description: "Avengers #0 (Oct 2015)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Cable",
    subTitle: "Nathan Summers",
    description: "Uncanny Avengers V3 #4 (Jan 2016)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Wasp",
    subTitle: "Nadia van Dyne",
    description: "All-Different Avengers #9 (May 2016)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Ghost Rider",
    subTitle: "Robbie Reyes",
    description: "The Avengers V8 #6 (Jul 2018)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Phoenix",
    subTitle: "Phoenix Force",
    description: "The Avengers V8 #54 (Mar 2022)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Starbrand",
    subTitle: "Brandy Selby",
    description: "The Avengers V8 #55 (Apr 2022)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
  {
    title: "Nighthawk",
    subTitle: "Kyle Richmond",
    description: "The Avengers V8 #55 (Apr 2022)",
    imageSrc: staticFile("marvel/Iron man.jpg"),
  },
];
