import { staticFile } from "remotion";

export const data = [
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Thanos",
    bottomTitle: "King Thanos",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Thor",
    bottomTitle: "Rune King Thor",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Dr. Doom",
    bottomTitle: "God Emperor",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Hulk",
    bottomTitle: "Entropy",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Venom",
    bottomTitle: "God of Light",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Rider",
    bottomTitle: "Cosmic",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Spider Man",
    bottomTitle: "Captain Universe Spider Man",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Wolverine",
    bottomTitle: "Phoenix Force Wolverine",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Hulk",
    bottomTitle: "World Breaker Hulk",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Iron Man",
    bottomTitle: "Godkiller Armor Mk II",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Captain America",
    bottomTitle: "Hydra Supreme",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Doctor Strange",
    bottomTitle: "Black Priest Strange",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Scarlet Witch",
    bottomTitle: "House of M Wanda",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Jean Grey",
    bottomTitle: "Dark Phoenix",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Cyclops",
    bottomTitle: "Phoenix Cyclops",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Storm",
    bottomTitle: "Goddess of Thunder",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Deadpool",
    bottomTitle: "With Cosmic Powers",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Magneto",
    bottomTitle: "Ultimate Magneto",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Rogue",
    bottomTitle: "Rogue with Multiple Powers",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Iceman",
    bottomTitle: "Omega Level Iceman",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Silver Surfer",
    bottomTitle: "Keeper",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Venom",
    bottomTitle: "Venom-Captain Universe",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Daredevil",
    bottomTitle: "King of Hell",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Moon Knight",
    bottomTitle: "Phoenix Force Moon Knight",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Captain Marvel",
    bottomTitle: "Binary",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Nova",
    bottomTitle: "Nova Prime",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Ms. Marvel",
    bottomTitle: "Venomized Ms. Marvel",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Black Panther",
    bottomTitle: "Herald of Galactus",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Antman",
    bottomTitle: "Ultron-Pym Antman",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Beast",
    bottomTitle: "Dark Beast",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Quicksilver",
    bottomTitle: "Son of Chaos",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Namor",
    bottomTitle: "Phoenix Namor",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Professor X",
    bottomTitle: "Onslaught",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Ms. Marvel",
    bottomTitle: "Kamala Kang",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Groot",
    bottomTitle: "Thor Groot",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Scarlet Witch",
    bottomTitle: "Goddess of Chaos",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Vision",
    bottomTitle: "HOI Vision",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Sentry",
    bottomTitle: "Merged Sentry",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Black Panther",
    bottomTitle: "Ghost Hammer",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Thing",
    bottomTitle: "Angrir",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Thing",
    bottomTitle: "Ultimate Thing",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Hulk",
    bottomTitle: "TOBA Hulk",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Captain America",
    bottomTitle: "Soldier Supreme",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Doctor Strange",
    bottomTitle: "Dr. Strangefate",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Iron Man",
    bottomTitle: "Iron God",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Daredevil",
    bottomTitle: "Daredevil 2099",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Nick Fury",
    bottomTitle: "Unseen",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Moon Knight",
    bottomTitle: "Spector",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Kitty Pryde",
    bottomTitle: "Black Vortex",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "She-Hulk",
    bottomTitle: "Winter-Hulk",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Spider-Gwen",
    bottomTitle: "Gwen-Venom",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Deadpool",
    bottomTitle: "Galactipool",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Professor X",
    bottomTitle: "Witch-King",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Adam Warlock",
    bottomTitle: "Living Tribunal",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Jean Grey",
    bottomTitle: "White Phoenix",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Spider-Man",
    bottomTitle: "Spider-Beyonder",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Wolverine",
    bottomTitle: "Old Man Phoenix",
  },
  {
    topImageSrc: staticFile("marvel/Iron man.jpg"),
    bottomImageSrc: staticFile("marvel/Captain America.jpg"),
    topTitle: "Black Widow",
    bottomTitle: "Worthy Window",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Iron Man",
    bottomTitle: "Iron Hammer",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Captain America",
    bottomTitle: "Supreme Commander",
  },
  {
    topImageSrc: staticFile("marvel/Thor.jpg"),
    bottomImageSrc: staticFile("marvel/hulk.jpg"),
    topTitle: "Miles Morales",
    bottomTitle: "Captain Universe",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/Iron man.jpg"),
    topTitle: "Silver Surfer",
    bottomTitle: "Worthy Surfer",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/IrCosmic Ghost Rion man.jpg"),
    topTitle: "Pushiner",
    bottomTitle: "Cosmic Ghost Rider",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/IrCosmic Ghost Rion man.jpg"),
    topTitle: "Hulk",
    bottomTitle: "Infinity Hulk",
  },
  {
    topImageSrc: staticFile("marvel/Black Widow.jpg"),
    bottomImageSrc: staticFile("marvel/IrCosmic Ghost Rion man.jpg"),
    topTitle: "Deadpool",
    bottomTitle: "Enternity Deadpool",
  },
];
