import { staticFile } from "remotion";
import { IMessage } from "../v1/MessageBubble";

export const messages: IMessage[] = [
  {
    sender: "Deidara",
    text: "Did you guys hear about that weird fox guy?",
    sendTime: "12:00",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
    effect: [
      {
        type: "audio",
        src: staticFile("chat/effect/ding.mp3"),
        start: 0,
      },
      {
        type: "audio",
        src: staticFile("chat/effect/dragon-studio-pop-402322.mp3"),
        start: 1,
      },
    ],
  },
  {
    sender: "Obito",
    text: "The one that punched you in the face 💀",
    sendTime: "12:01",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
    effect: [
      {
        type: "audio",
        src: staticFile("chat/effect/ding.mp3"),
        start: 0,
      },
      {
        type: "zoom",
        start: 0,
        to: 1,
      },
    ],
  },
  {
    sender: "Deidara",
    text: "Shut up Tobi !!!",
    sendTime: "12:02",
    time: 2,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Hidan",
    text: "What fox guy??",
    sendTime: "12:03",
    time: 2,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Deidara",
    text: "The one with the yellow hair",
    sendTime: "12:04",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Kakuzu",
    text: "That was the brat that attacked me",
    sendTime: "12:05",
    time: 4,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Obito",
    text: "Looks like someone got violated 💀💀",
    sendTime: "12:06",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Kakuzu",
    text: "Zip it Tobi !!!",
    sendTime: "12:07",
    time: 2,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Obito",
    text: "Opps. I almost forgot my zipper was down 🙂",
    sendTime: "12:08",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "Guys... You're missing the point here",
    sendTime: "12:09",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Zetsu",
    text: "What's the point?",
    sendTime: "12:10",
    time: 2,
    avatar: staticFile("chat/avatar/Zetsu.jpg"),
    textColor: "#588157",
  },
  {
    sender: "Deidara",
    text: "That brat is joining the akatsuki",
    sendTime: "12:11",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: "YIPEEEE",
    sendTime: "12:12",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "Why are you so excited?",
    sendTime: "12:13",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: "Cuz you guys are so booooriiing",
    sendTime: "12:14",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Kakuzu",
    text: "Huh?",
    sendTime: "12:15",
    time: 2,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Obito",
    text: "We need someone to brighten the place up",
    sendTime: "12:16",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "That's exactly why you're here",
    sendTime: "12:17",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Zetsu",
    text: "Yeah we don't need any other person",
    sendTime: "12:18",
    time: 4,
    avatar: staticFile("chat/avatar/Zetsu.jpg"),
    textColor: "#588157",
  },
  {
    sender: "Obito",
    text: "I still stick with Naruto!!!",
    sendTime: "12:19",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Hidan",
    text: "That brat is as annoying as you are",
    sendTime: "12:20",
    time: 4,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Obito",
    text: "Which is exactly why he's perfect!!!",
    sendTime: "12:21",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Kakuzu",
    text: "You're not making sense anymore",
    sendTime: "12:22",
    time: 4,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Deidara",
    text: "He never made sense to begin with",
    sendTime: "12:23",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: "Just think of it.",
    sendTime: "12:24",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Obito",
    text: "We could become ramen besties",
    sendTime: "12:25",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Obito",
    text: "And get stuck in the tree all day",
    sendTime: "12:26",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "That looks like stuff only you'd like to do",
    sendTime: "12:27",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: "That's the point!!!",
    sendTime: "12:28",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Kakuzu",
    text: "Let's just hope PAIN changes his mind",
    sendTime: "12:29",
    time: 4,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Hidan",
    text: "Where the heck is he??",
    sendTime: "12:30",
    time: 4,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Pain",
    text: "There's something called patience you know",
    sendTime: "12:31",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Hidan",
    text: "Anh you know damn well that I don't have that",
    sendTime: "12:32",
    time: 4,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Obito",
    text: "Yayyy. Finally where is he???",
    sendTime: "12:33",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Pain",
    text: "Where is who??",
    sendTime: "12:34",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Obito",
    text: "NARUTO. I thought he's coming",
    sendTime: "12:35",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "If you bring Naruto, then I'm leaving",
    sendTime: "12:36",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: "Nobody cares....",
    sendTime: "12:37",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "WHAT DID YOU SAY?!?!?!?!?!",
    sendTime: "12:38",
    time: 2,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Itachi",
    text: "Tone it down Deidara",
    sendTime: "12:39",
    time: 2,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Deidara",
    text: "Finally. Someone that has sense is here",
    sendTime: "12:40",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Itachi",
    text: "What's this about?",
    sendTime: "12:41",
    time: 2,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Deidara",
    text: "Naruto is joining the akatsuki",
    sendTime: "12:42",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Itachi",
    text: "Isn't he meant to be running away from us",
    sendTime: "12:43",
    time: 4,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Deidara",
    text: "That's exactly what I thought!!!",
    sendTime: "12:44",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Kakuzu",
    text: "You have some explaining to do buddy",
    sendTime: "12:45",
    time: 4,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Pain",
    text: "We need Naruto to help us",
    sendTime: "12:46",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Deidara",
    text: "Help us?!?! Help us with what?!",
    sendTime: "12:47",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Pain",
    text: "With capturing tailed beast.",
    sendTime: "12:48",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Zetsu",
    text: "How are you sure he won't betray us?",
    sendTime: "12:49",
    time: 4,
    avatar: staticFile("chat/avatar/Zetsu.jpg"),
    textColor: "#588157",
  },
  {
    sender: "Pain",
    text: "I'm not.",
    sendTime: "12:50",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Hidan",
    text: "SO HOW CAN WE TRUST HIM THEN?",
    sendTime: "12:51",
    time: 4,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Pain",
    text: "We can't.",
    sendTime: "12:52",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Deidara",
    text: "You're just as brain-dead as Tobi",
    sendTime: "12:53",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: "Heyy. I heard that !!!!",
    sendTime: "12:54",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "You were supposed to",
    sendTime: "12:55",
    time: 2,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Pain",
    text: "Konan, Go Call Naruto",
    sendTime: "12:56",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Konan",
    text: "I lost him",
    sendTime: "12:57",
    time: 2,
    avatar: staticFile("chat/avatar/Konan.jpg"),
    textColor: "#A663CC",
  },
  {
    sender: "Pain",
    text: "What?!!!. I thought he was following us",
    sendTime: "12:58",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Konan",
    text: "Relax. He's probably stuck in a tree again",
    sendTime: "12:59",
    time: 4,
    avatar: staticFile("chat/avatar/Konan.jpg"),
    textColor: "#A663CC",
  },
  {
    sender: "Konan",
    text: "Or trying to make friends with a squirrel",
    sendTime: "13:00",
    time: 4,
    avatar: staticFile("chat/avatar/Konan.jpg"),
    textColor: "#A663CC",
  },
  {
    sender: "Zetsu",
    text: "Found him. He's in the ramen shop down the street",
    sendTime: "13:01",
    time: 4,
    avatar: staticFile("chat/avatar/Zetsu.jpg"),
    textColor: "#588157",
  },
  {
    sender: "Pain",
    text: "Of course he is. Tell him to hurry up!",
    sendTime: "13:02",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Naruto",
    text: "Sorry guys! Got caught up in an intense ramen eating contest",
    sendTime: "13:03",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Obito",
    text: "Ooooh!!!. DID YOU WIN !!?",
    sendTime: "13:04",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Naruto",
    text: "You bet I did",
    sendTime: "13:05",
    time: 2,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Deidara",
    text: "Two Tobi's?! I'm gonna blow up",
    sendTime: "13:06",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Pain",
    text: "Relax Deidara. He hasn't been added yet",
    sendTime: "13:07",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Deidara",
    text: "WHAT??!!!. FINALLY you're come back to your senses",
    sendTime: "13:08",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Hidan",
    text: "Guys. Let's celebrate with a party",
    sendTime: "13:09",
    time: 4,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Kakuzu",
    text: "I'll get the cake",
    sendTime: "13:10",
    time: 2,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Pain",
    text: "I Wasn't done talking...",
    sendTime: "13:11",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Zetsu",
    text: "Huh??",
    sendTime: "13:12",
    time: 2,
    avatar: staticFile("chat/avatar/Zetsu.jpg"),
    textColor: "#588157",
  },
  {
    sender: "Pain",
    text: "Tobi will be the one deciding if he gets in or not",
    sendTime: "13:13",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Obito",
    text: "YIPEEEE",
    sendTime: "13:14",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "How in the world is that fair",
    sendTime: "13:15",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: "Tough luck ARTIST",
    sendTime: "13:16",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Obito",
    text: "But I'm gonna go with NO",
    sendTime: "13:17",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Obito",
    text: "I don't want NARUTO to stay here",
    sendTime: "13:18",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "Yesss... Finally",
    sendTime: "13:19",
    time: 2,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Obito",
    text: ".....Is what I would've said if I was DUMB",
    sendTime: "13:20",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Deidara",
    text: "You just had to spoil my mood didn't you",
    sendTime: "13:21",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Pain",
    text: "That doesn't matter. He already said yes",
    sendTime: "13:22",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Naruto",
    text: "So does that mean I'm a member now?",
    sendTime: "13:23",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Pain",
    text: "Yes. Just don't get Ramen stains on your new cloak",
    sendTime: "13:24",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Naruto",
    text: "I make zero promises",
    sendTime: "13:25",
    time: 2,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Itachi",
    text: "Can we just focus. We have a mission to discuss",
    sendTime: "13:26",
    time: 4,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Deidara",
    text: "I'm not going on a mission with that brat",
    sendTime: "13:27",
    time: 4,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Kakuzu",
    text: "Yeah me neither",
    sendTime: "13:28",
    time: 2,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Pain",
    text: "Quit behaving like Children",
    sendTime: "13:29",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Obito",
    text: "What he said !!!!!",
    sendTime: "13:30",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Itachi",
    text: "Naruto..... Do you even know what the akatsuki does?",
    sendTime: "13:31",
    time: 4,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Naruto",
    text: "Capturing Jinchurikis right? Piece of cake",
    sendTime: "13:32",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Deidara",
    text: "Famous Last words",
    sendTime: "13:33",
    time: 2,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Pain",
    text: "Zip it! No one is capturing Naruto",
    sendTime: "13:34",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Hidan",
    text: "Ugh...  Quit being so boring",
    sendTime: "13:35",
    time: 4,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Itachi",
    text: "GUYSS!!! THE PLAN",
    sendTime: "13:36",
    time: 2,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Pain",
    text: "Oh right... As I was saying... We infiltrate the hidden leaf village tonight",
    sendTime: "13:37",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Naruto",
    text: "But I thought we're meant to be good guys now!",
    sendTime: "13:38",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Itachi",
    text: "NARUTO... WE'RE CRIMINALS!!!",
    sendTime: "13:39",
    time: 2,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Naruto",
    text: "Speak for yourself. I'm just here for the puppet shows",
    sendTime: "13:40",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Pain",
    text: "Can we focus please?",
    sendTime: "13:41",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Naruto",
    text: "Fine, but can I at least wear my hokage hat",
    sendTime: "13:42",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Pain",
    text: "No we're trying to be sneaky",
    sendTime: "13:43",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Obito",
    text: "Ooh! Can I wear the Kokage hat?",
    sendTime: "13:44",
    time: 4,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Pain",
    text: "You have to be kidding me",
    sendTime: "13:45",
    time: 4,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Naruto",
    text: "Ugh this is so boring. I quit",
    sendTime: "13:46",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Obito",
    text: "WHAT WHY?!?!?!?",
    sendTime: "13:47",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "Naruto",
    text: "I came here to help Itachi spy on you guys. It's becoming boring now",
    sendTime: "13:48",
    time: 4,
    avatar: staticFile("chat/avatar/Naruto.jpg"),
    textColor: "#FB8B24",
  },
  {
    sender: "Obito",
    text: "Noooo. Don't goooo !!!",
    sendTime: "13:49",
    time: 2,
    avatar: staticFile("chat/avatar/Obito.jpg"),
    textColor: "#EB5E28",
  },
  {
    sender: "",
    text: "Naruto left the group",
    sendTime: "13:50",
    action: "left",
    time: 2,
    avatar: "",
    textColor: "#ffffff",
  },
  {
    sender: "Deidara",
    text: "Finally... He's gone",
    sendTime: "13:51",
    time: 2,
    avatar: staticFile("chat/avatar/Deidara.jpg"),
    textColor: "#E09F3E",
  },
  {
    sender: "Hidan",
    text: "Let's celebrate",
    sendTime: "13:52",
    time: 2,
    avatar: staticFile("chat/avatar/Hidan.jpg"),
    textColor: "#7D7D7D",
  },
  {
    sender: "Kakuzu",
    text: "I'll get the cake this time",
    sendTime: "13:53",
    time: 4,
    avatar: staticFile("chat/avatar/Kakuzu.jpg"),
    textColor: "#335C67",
  },
  {
    sender: "Pain",
    text: "Guys, hold on.....",
    sendTime: "13:54",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Pain",
    text: "You forgot about itachi",
    sendTime: "13:55",
    time: 2,
    avatar: staticFile("chat/avatar/Pain.jpg"),
    textColor: "#9E2A2B",
  },
  {
    sender: "Zetsu",
    text: "Is it true you've been spying on us ITACHI?",
    sendTime: "13:56",
    time: 4,
    avatar: staticFile("chat/avatar/Zetsu.jpg"),
    textColor: "#588157",
  },
  {
    sender: "Itachi",
    text: "Ummm.....",
    sendTime: "13:57",
    time: 2,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
  {
    sender: "Itachi",
    text: "NO SPEAK ENGLISH",
    sendTime: "13:58",
    time: 2,
    avatar: staticFile("chat/avatar/Itachi.jpg"),
    textColor: "#D00000",
  },
];

export default messages;
