export type StaticFileName =
  | "marvel/2192748.jpg"
  | "marvel/Black Widow.jpg"
  | "marvel/Captain America.jpg"
  | "marvel/Iron man.jpg"
  | "marvel/Spiderman (miles morales).jpg"
  | "marvel/Thor.jpg"
  | "marvel/dc.png"
  | "marvel/ending.mp4"
  | "marvel/hulk.jpg"
  | "marvel/marvel.jpg"
  | "anime/hot-search-2025/Call of the Night.png"
  | "anime/hot-search-2025/Dandadan.png"
  | "anime/hot-search-2025/Demon Slayer.png"
  | "anime/hot-search-2025/Dr. Stone Science Future.png"
  | "anime/hot-search-2025/Dragon Ball Daima.png"
  | "anime/hot-search-2025/Gachiakuta.png"
  | "anime/hot-search-2025/Kaiju No. 8.png"
  | "anime/hot-search-2025/Mobile Suit Gundam GQuuuuuuX.png"
  | "anime/hot-search-2025/My Dress-Up Darling.png"
  | "anime/hot-search-2025/My Hero Academia.png"
  | "anime/hot-search-2025/One Piece.png"
  | "anime/hot-search-2025/Re Zero.png"
  | "anime/hot-search-2025/Sakamoto Days.png"
  | "anime/hot-search-2025/Spy x Family.png"
  | "anime/hot-search-2025/Takopi's Original Sin.png"
  | "anime/hot-search-2025/The Apothecary Diaries.png"
  | "anime/hot-search-2025/apocalypse-hotel.png"
  | "anime/hot-search-2025/ave-mujica.png"
  | "anime/hot-search-2025/honey-lemon-soda.png"
  | "anime/hot-search-2025/lazarus.png"
  | "anime/hot-search-2025/medalist.png"
  | "anime/hot-search-2025/my-happy-marriage.png"
  | "anime/hot-search-2025/solo-leveling.png"
  | "anime/hot-search-2025/the-summer-hikaru-died.png"
  | "anime/hot-search-2025/zenshu.png";
