export const EXHIBITION_DATA = [
  {
    id: 1,
    title: "Hashirama Senju",
    description: "Wood Release & Healing\nGod of Shinobi",
    imageUrl: "/anime/hokage/Hashirama Senju.jpg",
    powerLevel: 9800,
    tier: "God-Level",
  },
  {
    id: 2,
    title: "Tobirama Senju",
    description: "Space-Time & Water Release\nCreator of Jutsu",
    imageUrl: "/anime/hokage/Tobirama Senju.jpg",
    powerLevel: 8500,
    tier: "Kage-Level",
  },
  {
    id: 3,
    title: "Hiruzen Sarutobi",
    description: "All Five Elements\nThe Professor",
    imageUrl: "/anime/hokage/Hiruzen Sarutobi.jpg",
    powerLevel: 7800,
    tier: "Kage-Level",
  },
  {
    id: 4,
    title: "Minato Namikaze",
    description: "Space-Time & Rasengan\nYellow Flash",
    imageUrl: "/anime/hokage/Minato Namikaze.jpg",
    powerLevel: 9200,
    tier: "Elite-Level",
  },
  // {
  //   id: 5,
  //   title: "Tsunade Senju",
  //   description: "Strength of a Hundred Seal\nLegendary Sannin",
  //   imageUrl: "/anime/hokage/Tsunade Senju.jpg",
  //   powerLevel: 8200,
  //   tier: "Kage-Level",
  // },
  // {
  //   id: 6,
  //   title: "Kakashi Hatake",
  //   description: "Sharingan & Lightning\nCopy Ninja",
  //   imageUrl: "/anime/hokage/Kakashi Hatake.jpg",
  //   powerLevel: 8700,
  //   tier: "Elite-Level",
  // },
  // {
  //   id: 7,
  //   title: "Naruto Uzumaki",
  //   description: "Nine-Tails & Sage of Six Paths\nHero of the Hidden Leaf",
  //   imageUrl: "/anime/hokage/Naruto Uzumaki.jpg",
  //   powerLevel: 9999,
  //   tier: "God-Level",
  // },
  // {
  //   id: 8,
  //   title: "Shikamaru Nara",
  //   description: "Shadow Techniques\nMaster Strategist",
  //   imageUrl: "/anime/hokage/Shikamaru Nara.jpg",
  //   powerLevel: 6500,
  //   tier: "Jonin-Level",
  // },
];
