import { staticFile } from "remotion";

export const data = [
  {
    topTitle: "Marin Kitagawa",
    topImageSrc: staticFile("anime/best-anime-couples/Marin Kitagawa.jfif"),
    bottomTitle: "Wakana Gojo",
    bottomImageSrc: staticFile("anime/best-anime-couples/Wakana Gojo.jfif"),
    description: "My Dress-Up Darling",
  },
  {
    topTitle: "Chizuru Mizuhara",
    topImageSrc: staticFile("anime/best-anime-couples/Chizuru Mizuhara.jfif"),
    bottomTitle: "Kazuya Kinoshita",
    bottomImageSrc: staticFile(
      "anime/best-anime-couples/Kazuya Kinoshita.jfif",
    ),
    description: "Rent-a-Girlfriend",
    topObjectPosition: {
      x: 0,
      y: 94,
    },
    topZoom: 1,
  },
  {
    topTitle: "Komi Shouko",
    topImageSrc: staticFile("anime/best-anime-couples/Komi Shouko.jfif"),
    bottomTitle: "Hitohito Tadano",
    bottomImageSrc: staticFile("anime/best-anime-couples/Hitohito Tadano.jfif"),
    description: "Komi Can't Communicate",
  },
  {
    topTitle: "Kyoko Hori",
    topImageSrc: staticFile("anime/best-anime-couples/Kyoko Hori.jfif"),
    bottomTitle: "Izumi Miyamura",
    bottomImageSrc: staticFile("anime/best-anime-couples/Izumi Miyamura.jfif"),
    description: "Horimiya",
    topObjectPosition: {
      x: 0,
      y: 86,
    },
  },
  {
    topTitle: "Kaguya Shinomiya",
    topImageSrc: staticFile("anime/best-anime-couples/Kaguya Shinomiya.jfif"),
    bottomTitle: "Miyuki Shirogane",
    bottomImageSrc: staticFile(
      "anime/best-anime-couples/Miyuki Shirogane.jfif",
    ),
    description: "Kaguya-sama: Love is War",
  },
  {
    topTitle: "Mai Sakurajima",
    topImageSrc: staticFile("anime/best-anime-couples/Mai Sakurajima.jfif"),
    bottomTitle: "Sakuta Azusagawa",
    bottomImageSrc: staticFile(
      "anime/best-anime-couples/Sakuta Azusagawa.jfif",
    ),
    description: "Rascal Does Not Dream of Bunny Girl Senpai",
  },
  {
    topTitle: "Yukino Yukinoshita",
    topImageSrc: staticFile("anime/best-anime-couples/Yukino Yukinoshita.jfif"),
    bottomTitle: "Hachiman Hikigaya",
    bottomImageSrc: staticFile(
      "anime/best-anime-couples/Hachiman Hikigaya.jfif",
    ),
    description: "My Teen Romantic Comedy SNAFU",
  },
  {
    topTitle: "Emilia",
    topImageSrc: staticFile("anime/best-anime-couples/Emilia.jfif"),
    bottomTitle: "Subaru Natsuki",
    bottomImageSrc: staticFile("anime/best-anime-couples/Subaru Natsuki.jfif"),
    description: "Re:Zero",
  },
  {
    topTitle: "Megumin",
    topImageSrc: staticFile("anime/best-anime-couples/Megumin.jfif"),
    bottomTitle: "Kazuma Satou",
    bottomImageSrc: staticFile("anime/best-anime-couples/Kazuma Satou.jfif"),
    description: "KonoSuba",
  },
  {
    topTitle: "Raphtalia",
    topImageSrc: staticFile("anime/best-anime-couples/Raphtalia.jfif"),
    bottomTitle: "Naofumi Iwatani",
    bottomImageSrc: staticFile("anime/best-anime-couples/Naofumi Iwatani.jfif"),
    description: "The Rising of the Shield Hero",
  },
  {
    topTitle: "Zero Two",
    topImageSrc: staticFile("anime/best-anime-couples/Zero Two.jfif"),
    bottomTitle: "Hiro",
    bottomImageSrc: staticFile("anime/best-anime-couples/Hiro.jfif"),
    description: "Darling in the Franxx",
  },
  {
    topTitle: "Tsukasa Yuzaki",
    topImageSrc: staticFile("anime/best-anime-couples/Tsukasa Yuzaki.jfif"),
    bottomTitle: "Nasa Yuzaki",
    bottomImageSrc: staticFile("anime/best-anime-couples/Nasa Yuzaki.jfif"),
    description: "Tonikaku Kawaii",
  },
  {
    topTitle: "Yor Forger",
    topImageSrc: staticFile("anime/best-anime-couples/Yor Forger.jfif"),
    bottomTitle: "Loid Forger",
    bottomImageSrc: staticFile("anime/best-anime-couples/Loid Forger.jfif"),
    description: "Spy x Family",
  },
  {
    topTitle: "Shoko Nishimiya",
    topImageSrc: staticFile("anime/best-anime-couples/Shoko Nishimiya.jfif"),
    bottomTitle: "Shoya Ishida",
    bottomImageSrc: staticFile("anime/best-anime-couples/Shoya Ishida.jfif"),
    description: "A Silent Voice",
  },
  {
    topTitle: "Mitsuha Miyamizu",
    topImageSrc: staticFile("anime/best-anime-couples/Mitsuha Miyamizu.jfif"),
    bottomTitle: "Taki Tachibana",
    bottomImageSrc: staticFile("anime/best-anime-couples/Taki Tachibana.jfif"),
    description: "Your Name",
  },
  {
    topTitle: "Hina Amano",
    topImageSrc: staticFile("anime/best-anime-couples/Hina Amano.jfif"),
    bottomTitle: "Hodaka Morishima",
    bottomImageSrc: staticFile(
      "anime/best-anime-couples/Hodaka Morishima.jfif",
    ),
    description: "Weathering With You",
  },
  {
    topTitle: "Kaori Miyazono",
    topImageSrc: staticFile("anime/best-anime-couples/Kaori Miyazono.jfif"),
    bottomTitle: "Kousei Arima",
    bottomImageSrc: staticFile("anime/best-anime-couples/Kousei Arima.jfif"),
    description: "Your Lie in April",
  },
  {
    topTitle: "Taiga Aisaka",
    topImageSrc: staticFile("anime/best-anime-couples/Taiga Aisaka.jfif"),
    bottomTitle: "Ryuuji Takasu",
    bottomImageSrc: staticFile("anime/best-anime-couples/Ryuuji Takasu.jfif"),
    description: "Toradora!",
  },
  {
    topTitle: "Nagisa Furukawa",
    topImageSrc: staticFile("anime/best-anime-couples/Nagisa Furukawa.jfif"),
    bottomTitle: "Tomoya Okazaki",
    bottomImageSrc: staticFile("anime/best-anime-couples/Tomoya Okazaki.jfif"),
    description: "Clannad",
  },
  {
    topTitle: "Kurisu Makise",
    topImageSrc: staticFile("anime/best-anime-couples/Kurisu Makise.jfif"),
    bottomTitle: "Rintarou Okabe",
    bottomImageSrc: staticFile("anime/best-anime-couples/Rintarou Okabe.jfif"),
    description: "Steins;Gate",
  },
  {
    topTitle: "Asuna Yuuki",
    topImageSrc: staticFile("anime/best-anime-couples/Asuna Yuuki.jfif"),
    bottomTitle: "Kazuto Kirigaya",
    bottomImageSrc: staticFile("anime/best-anime-couples/Kazuto Kirigaya.jfif"),
    description: "Sword Art Online",
    bottomObjectPosition: {
      x: 0,
      y: 209,
    },
    topObjectPosition: {
      x: 0,
      y: 97,
    },
  },
  {
    topTitle: "Hinata Hyuuga",
    topImageSrc: staticFile("anime/best-anime-couples/Hinata Hyuuga.jfif"),
    bottomTitle: "Naruto Uzumaki",
    bottomImageSrc: staticFile("anime/best-anime-couples/Naruto Uzumaki.jfif"),
    description: "Naruto",
    topObjectPosition: {
      x: 0,
      y: 129,
    },
  },
  {
    topTitle: "Sakura Haruno",
    topImageSrc: staticFile("anime/best-anime-couples/Sakura Haruno.jfif"),
    bottomTitle: "Sasuke Uchiha",
    bottomImageSrc: staticFile("anime/best-anime-couples/Sasuke Uchiha.jfif"),
    description: "Naruto",
    topObjectPosition: {
      x: 0,
      y: 216,
    },
    bottomObjectPosition: {
      x: 0,
      y: 102,
    },
  },
  {
    topTitle: "Kushina Uzumaki",
    topImageSrc: staticFile("anime/best-anime-couples/Kushina Uzumaki.jfif"),
    bottomTitle: "Minato Namikaze",
    bottomImageSrc: staticFile("anime/best-anime-couples/Minato Namikaze.jfif"),
    description: "Naruto",
    topObjectPosition: {
      x: 0,
      y: 164,
    },
  },
  {
    topTitle: "Temari",
    topImageSrc: staticFile("anime/best-anime-couples/Temari.jfif"),
    bottomTitle: "Shikamaru Nara",
    bottomImageSrc: staticFile("anime/best-anime-couples/Shikamaru Nara.jfif"),
    description: "Naruto",
  },
  {
    topTitle: "Winry Rockbell",
    topImageSrc: staticFile("anime/best-anime-couples/Winry Rockbell.jfif"),
    bottomTitle: "Edward Elric",
    bottomImageSrc: staticFile("anime/best-anime-couples/Edward Elric.jfif"),
    description: "Fullmetal Alchemist: Brotherhood",
  },
  {
    topTitle: "Riza Hawkeye",
    topImageSrc: staticFile("anime/best-anime-couples/Riza Hawkeye.jfif"),
    bottomTitle: "Roy Mustang",
    bottomImageSrc: staticFile("anime/best-anime-couples/Roy Mustang.jfif"),
    description: "Fullmetal Alchemist: Brotherhood",
    topObjectPosition: {
      x: 0,
      y: 252,
    },
    bottomObjectPosition: {
      x: 0,
      y: 325,
    },
  },
  {
    topTitle: "Kagome Higurashi",
    topImageSrc: staticFile("anime/best-anime-couples/Kagome Higurashi.jfif"),
    bottomTitle: "Inuyasha",
    bottomImageSrc: staticFile("anime/best-anime-couples/Inuyasha.jfif"),
    description: "Inuyasha",
    topObjectPosition: {
      x: 0,
      y: 115,
    },
    bottomObjectPosition: {
      x: 0,
      y: 329,
    },
  },
  {
    topTitle: "Sango",
    topImageSrc: staticFile("anime/best-anime-couples/Sango.jfif"),
    bottomTitle: "Miroku",
    bottomImageSrc: staticFile("anime/best-anime-couples/Miroku.jfif"),
    description: "Inuyasha",
    topObjectPosition: {
      x: 0,
      y: 279,
    },
  },
  {
    topTitle: "Tohru Honda",
    topImageSrc: staticFile("anime/best-anime-couples/Tohru Honda.jfif"),
    bottomTitle: "Kyo Sohma",
    bottomImageSrc: staticFile("anime/best-anime-couples/Kyo Sohma.jfif"),
    description: "Fruits Basket",
  },
  {
    topTitle: "Misaki Ayuzawa",
    topImageSrc: staticFile("anime/best-anime-couples/Misaki Ayuzawa.jfif"),
    bottomTitle: "Takumi Usui",
    bottomImageSrc: staticFile("anime/best-anime-couples/Takumi Usui.jfif"),
    description: "Maid Sama!",
  },
  {
    topTitle: "Shirayuki",
    topImageSrc: staticFile("anime/best-anime-couples/Shirayuki.jfif"),
    bottomTitle: "Zen Wistaria",
    bottomImageSrc: staticFile("anime/best-anime-couples/Zen Wistaria.jfif"),
    description: "Snow White with the Red Hair",
  },
  {
    topTitle: "Yona",
    topImageSrc: staticFile("anime/best-anime-couples/Yona.jfif"),
    bottomTitle: "Hak Son",
    bottomImageSrc: staticFile("anime/best-anime-couples/Hak Son.jfif"),
    description: "Yona of the Dawn",
    bottomObjectPosition: {
      x: 0,
      y: 114,
    },
  },
  {
    topTitle: "Nanami Momozono",
    topImageSrc: staticFile("anime/best-anime-couples/Nanami Momozono.jfif"),
    bottomTitle: "Tomoe",
    bottomImageSrc: staticFile("anime/best-anime-couples/Tomoe.jfif"),
    description: "Kamisama Kiss",
    bottomObjectPosition: {
      x: 0,
      y: 70,
    },
  },
  {
    topTitle: "Futaba Yoshioka",
    topImageSrc: staticFile("anime/best-anime-couples/Futaba Yoshioka.jfif"),
    bottomTitle: "Kou Mabuchi",
    bottomImageSrc: staticFile("anime/best-anime-couples/Kou Mabuchi.jfif"),
    description: "Blue Spring Ride",
  },
  {
    topTitle: "Sawako Kuronuma",
    topImageSrc: staticFile("anime/best-anime-couples/Sawako Kuronuma.jfif"),
    bottomTitle: "Shota Kazehaya",
    bottomImageSrc: staticFile("anime/best-anime-couples/Shota Kazehaya.jfif"),
    description: "Kimi ni Todoke",
  },
  {
    topTitle: "Mei Tachibana",
    topImageSrc: staticFile("anime/best-anime-couples/Mei Tachibana.jfif"),
    bottomTitle: "Yamato Kurosawa",
    bottomImageSrc: staticFile("anime/best-anime-couples/Yamato Kurosawa.jfif"),
    description: "Say 'I Love You'.",
  },
  {
    topTitle: "Shizuku Mizutani",
    topImageSrc: staticFile("anime/best-anime-couples/Shizuku Mizutani.jfif"),
    bottomTitle: "Haru Yoshida",
    bottomImageSrc: staticFile("anime/best-anime-couples/Haru Yoshida.jfif"),
    description: "My Little Monster",
  },
  {
    topTitle: "Eru Chitanda",
    topImageSrc: staticFile("anime/best-anime-couples/Eru Chitanda.jfif"),
    bottomTitle: "Houtarou Oreki",
    bottomImageSrc: staticFile("anime/best-anime-couples/Houtarou Oreki.jfif"),
    description: "Hyouka",
  },
  {
    topTitle: "Mirai Kuriyama",
    topImageSrc: staticFile("anime/best-anime-couples/Mirai Kuriyama.jfif"),
    bottomTitle: "Akihito Kanbara",
    bottomImageSrc: staticFile("anime/best-anime-couples/Akihito Kanbara.jfif"),
    description: "Beyond the Boundary",
  },
  {
    topTitle: "Rikka Takanashi",
    topImageSrc: staticFile("anime/best-anime-couples/Rikka Takanashi.jfif"),
    bottomTitle: "Yuuta Togashi",
    bottomImageSrc: staticFile("anime/best-anime-couples/Yuuta Togashi.jfif"),
    description: "Love, Chunibyo & Other Delusions",
  },
  {
    topTitle: "Saber",
    topImageSrc: staticFile("anime/best-anime-couples/Saber.jfif"),
    bottomTitle: "Shirou Emiya",
    bottomImageSrc: staticFile("anime/best-anime-couples/Shirou Emiya.jfif"),
    description: "Fate/stay night",
  },
  {
    topTitle: "Lucy Heartfilia",
    topImageSrc: staticFile("anime/best-anime-couples/Lucy Heartfilia.jfif"),
    bottomTitle: "Natsu Dragneel",
    bottomImageSrc: staticFile("anime/best-anime-couples/Natsu Dragneel.jfif"),
    description: "Fairy Tail",
  },
  {
    topTitle: "Juvia Lockser",
    topImageSrc: staticFile("anime/best-anime-couples/Juvia Lockser.jfif"),
    bottomTitle: "Gray Fullbuster",
    bottomImageSrc: staticFile("anime/best-anime-couples/Gray Fullbuster.jfif"),
    description: "Fairy Tail",
  },
  {
    topTitle: "Levy McGarden",
    topImageSrc: staticFile("anime/best-anime-couples/Levy McGarden.jfif"),
    bottomTitle: "Gajeel Redfox",
    bottomImageSrc: staticFile("anime/best-anime-couples/Gajeel Redfox.jfif"),
    description: "Fairy Tail",
  },
  {
    topTitle: "Orihime Inoue",
    topImageSrc: staticFile("anime/best-anime-couples/Orihime Inoue.jfif"),
    bottomTitle: "Ichigo Kurosaki",
    bottomImageSrc: staticFile("anime/best-anime-couples/Ichigo Kurosaki.jfif"),
    description: "Bleach",
    topObjectPosition: {
      x: 0,
      y: 174,
    },
  },
  {
    topTitle: "Rukia Kuchiki",
    topImageSrc: staticFile("anime/best-anime-couples/Rukia Kuchiki.jfif"),
    bottomTitle: "Renji Abarai",
    bottomImageSrc: staticFile("anime/best-anime-couples/Renji Abarai.jfif"),
    description: "Bleach",
  },
  {
    topTitle: "Nezuko Kamado",
    topImageSrc: staticFile("anime/best-anime-couples/Nezuko Kamado.jfif"),
    bottomTitle: "Zenitsu Agatsuma",
    bottomImageSrc: staticFile(
      "anime/best-anime-couples/Zenitsu Agatsuma.jfif",
    ),
    description: "Demon Slayer",
  },
  {
    topTitle: "Kanao Tsuyuri",
    topImageSrc: staticFile("anime/best-anime-couples/Kanao Tsuyuri.jfif"),
    bottomTitle: "Tanjiro Kamado",
    bottomImageSrc: staticFile("anime/best-anime-couples/Tanjiro Kamado.jfif"),
    description: "Demon Slayer",
  },
  {
    topTitle: "Mitsuri Kanroji",
    topImageSrc: staticFile("anime/best-anime-couples/Mitsuri Kanroji.jfif"),
    bottomTitle: "Obanai Iguro",
    bottomImageSrc: staticFile("anime/best-anime-couples/Obanai Iguro.jfif"),
    description: "Demon Slayer",
  },
  {
    topTitle: "Elizabeth Liones",
    topImageSrc: staticFile("anime/best-anime-couples/Elizabeth Liones.jfif"),
    bottomTitle: "Meliodas",
    bottomImageSrc: staticFile("anime/best-anime-couples/Meliodas.jfif"),
    description: "The Seven Deadly Sins",
  },
  {
    topTitle: "Diane",
    topImageSrc: staticFile("anime/best-anime-couples/Diane.jfif"),
    bottomTitle: "King",
    bottomImageSrc: staticFile("anime/best-anime-couples/King.jfif"),
    description: "The Seven Deadly Sins",
  },
  {
    topTitle: "Elaine",
    topImageSrc: staticFile("anime/best-anime-couples/Elaine.jfif"),
    bottomTitle: "Ban",
    bottomImageSrc: staticFile("anime/best-anime-couples/Ban.jfif"),
    description: "The Seven Deadly Sins",
  },
  {
    topTitle: "Ochaco Uraraka",
    topImageSrc: staticFile("anime/best-anime-couples/Ochaco Uraraka.jfif"),
    bottomTitle: "Izuku Midoriya",
    bottomImageSrc: staticFile("anime/best-anime-couples/Izuku Midoriya.jfif"),
    description: "My Hero Academia",
  },
  {
    topTitle: "Misa Amane",
    topImageSrc: staticFile("anime/best-anime-couples/Misa Amane.jfif"),
    bottomTitle: "Light Yagami",
    bottomImageSrc: staticFile("anime/best-anime-couples/Light Yagami.jfif"),
    description: "Death Note",
  },
  {
    topTitle: "C.C.",
    topImageSrc: staticFile("anime/best-anime-couples/C.C..jfif"),
    bottomTitle: "Lelouch vi Britannia",
    bottomImageSrc: staticFile(
      "anime/best-anime-couples/Lelouch vi Britannia.jfif",
    ),
    description: "Code Geass",
  },
  {
    topTitle: "Mikasa Ackerman",
    topImageSrc: staticFile("anime/best-anime-couples/Mikasa Ackerman.jfif"),
    bottomTitle: "Eren Yeager",
    bottomImageSrc: staticFile("anime/best-anime-couples/Eren Yeager.jfif"),
    description: "Attack on Titan",
  },
];
