import { staticFile } from "remotion";
import { SingleImageData } from "../SingleImageCard/SingleImageCard";

export const data: SingleImageData[] = [
  {
    title: "Kanata Izumi",
    description: "17",
    subTitle: "Lucky Star",
    imageSrc: staticFile("anime/girl-older-than-age/Kanata Izumi.jfif"),
    objectPosition: { x: 0, y: 40 },
  },
  {
    title: "Illyasviel von Einzbern",
    description: "18",
    subTitle: "Fate Series",
    imageSrc: staticFile(
      "anime/girl-older-than-age/illyasviel von einzbern.jfif",
    ),
    objectPosition: {
      x: -7,
      y: 5,
    },
    zoom: 2.7,
  },
  {
    title: "Mafuyu Hoshikawa",
    description: "20",
    subTitle: "Blend-S",
    imageSrc: staticFile("anime/girl-older-than-age/Mafuyu hoshikawa.jfif"),
  },
  {
    title: "Maho Hiyajo",
    description: "21",
    subTitle: "Steins;Gate",
    imageSrc: staticFile("anime/girl-older-than-age/Maho Hiyajo.jfif"),
  },
  {
    title: "Sugar",
    description: "22",
    subTitle: "One Piece",
    imageSrc: staticFile("anime/girl-older-than-age/Sugar.jfif"),
  },
  {
    title: "Manami Aiba",
    description: "22",
    subTitle: "My Hero Academia",
    imageSrc: staticFile("anime/girl-older-than-age/Manami Aiba.jfif"),
  },
  {
    title: "Futaba Igarashi",
    description: "23",
    subTitle: "My Senpai is Annoying",
    imageSrc: staticFile("anime/girl-older-than-age/Futaba Igarashi.jfif"),
  },
  {
    title: "Tatsumaki",
    description: "28",
    subTitle: "One Punch Man",
    imageSrc: staticFile("anime/girl-older-than-age/Tatsumaki.jfif"),
  },
  {
    title: "Utage Douraku",
    description: "29",
    subTitle: "Noucome",
    imageSrc: staticFile("anime/girl-older-than-age/Utage Douraku.jfif"),
    objectPosition: { x: 0, y: 145 },
  },
  {
    title: "Jun Shiomi",
    description: "34",
    subTitle: "Food Wars",
    imageSrc: staticFile("anime/girl-older-than-age/Jun shiomi.jfif"),
  },
  // {
  //   title: "Tsukuyomi Komoe",
  //   description: "35",
  //   subTitle: "Toaru Majutsu no Index",
  //   imageSrc: staticFile("anime/girl-older-than-age/Tsukuyomi Komoe.webp"),
  // },
  // {
  //   title: "Nazuna Nanakusa",
  //   description: "40",
  //   subTitle: "Call of the Night",
  //   imageSrc: staticFile("anime/girl-older-than-age/Nazuna nanakusa.jfif"),
  //   objectPosition: { x: 0, y: 157 },
  // },
  // {
  //   title: "Kinue Hayase",
  //   description: "42",
  //   subTitle: "Masamune-kun's Revenge",
  //   imageSrc: staticFile("anime/girl-older-than-age/Kinue Hayase.jfif"),
  // },
  // {
  //   title: "Roxy Migurdia",
  //   description: "44",
  //   subTitle: "Mushoku Tensei",
  //   imageSrc: staticFile("anime/girl-older-than-age/Roxy migurdia.jfif"),
  // },
  // {
  //   title: "Lisa Lisa",
  //   description: "50",
  //   subTitle: "Jojo",
  //   imageSrc: staticFile("anime/girl-older-than-age/Lisa Lisa.jfif"),
  // },
  // {
  //   title: "Roma Hoito",
  //   description: "51",
  //   subTitle: "Tokyo Ghoul",
  //   imageSrc: staticFile("anime/girl-older-than-age/Roma Hoito.jfif"),
  // },
  // {
  //   title: "Biscuit Krueger",
  //   description: "57",
  //   subTitle: "Hunter x Hunter",
  //   imageSrc: staticFile("anime/girl-older-than-age/Biscuit kruegar.jfif"),
  // },
  // {
  //   title: "Narberal Gamma",
  //   description: "70+",
  //   subTitle: "Overlord",
  //   imageSrc: staticFile("anime/girl-older-than-age/Narberal Gamma.jfif"),
  // },
  // {
  //   title: "Shizue Izawa",
  //   description: "80",
  //   subTitle: "Tensura",
  //   imageSrc: staticFile("anime/girl-older-than-age/Shizue izawa.jfif"),
  // },
  // {
  //   title: "Yaku Yakuzen",
  //   description: "89",
  //   subTitle: "100Kanojo",
  //   imageSrc: staticFile("anime/girl-older-than-age/Yaku yakuzen.jfif"),
  //   objectPosition: { x: 0, y: 90 },
  // },
  // // {
  // //   title: "Krebskulm",
  // //   description: "100+",
  // //   subTitle: "How Not to Summon a Demon Lord",
  // //   imageSrc: "",
  // // },
  // {
  //   title: "Emilia",
  //   description: "114",
  //   subTitle: "Re:Zero",
  //   imageSrc: staticFile("anime/girl-older-than-age/Emilia.jfif"),
  // },
  // {
  //   title: "Mavis Vermillion",
  //   description: "118",
  //   subTitle: "Fairy Tail",
  //   imageSrc: staticFile("anime/girl-older-than-age/Mavis vermillion.jfif"),
  // },
  // {
  //   title: "Shalltear Bloodfallen",
  //   description: "200+",
  //   subTitle: "Overlord",
  //   imageSrc: staticFile(
  //     "anime/girl-older-than-age/Shalltear Bloodfallen.jfif",
  //   ),
  // },
  // {
  //   title: "Schwi Dola ",
  //   description: "211",
  //   subTitle: "No Game No Life",
  //   imageSrc: staticFile("anime/girl-older-than-age/Schwi dola.jfif"),
  // },
  // {
  //   title: "Evileye",
  //   description: "250",
  //   subTitle: "Overlord",
  //   imageSrc: staticFile("anime/girl-older-than-age/Evileye.jfif"),
  // },
  // {
  //   title: "Roux Cristasse",
  //   description: "300+",
  //   subTitle: "The Dawn of the Witch",
  //   imageSrc: staticFile("anime/girl-older-than-age/Roux Cristasse.jfif"),
  // },
  // {
  //   title: "Yue",
  //   description: "323",
  //   subTitle: "Arifureta",
  //   imageSrc: staticFile("anime/girl-older-than-age/Yue.jfif"),
  // },
  // {
  //   title: "Ai Enma",
  //   description: "400",
  //   subTitle: "Hell Girl",
  //   imageSrc: staticFile("anime/girl-older-than-age/Enma Ai.jfif"),
  // },
  // {
  //   title: "Beatrice",
  //   description: "400",
  //   subTitle: "Re:Zero",
  //   imageSrc: staticFile("anime/girl-older-than-age/Beatrice.jfif"),
  // },
  // {
  //   title: "Nero",
  //   description: "500",
  //   subTitle: "Black Clover",
  //   imageSrc: staticFile("anime/girl-older-than-age/Nero.jfif"),
  //   objectPosition: { x: 0, y: 110 },
  // },
  // {
  //   title: "Yuri Ha Zahad",
  //   description: "500+",
  //   subTitle: "Tower of God",
  //   imageSrc: staticFile("anime/girl-older-than-age/Yuri ha zahad.jfif"),
  // },
  // {
  //   title: "Flandre Scarlet",
  //   description: "517",
  //   subTitle: "Touhou",
  //   imageSrc: staticFile("anime/girl-older-than-age/Flandre Scarlet.jfif"),
  // },
  // {
  //   title: "C.C.",
  //   description: "550",
  //   subTitle: "Code Geass",
  //   imageSrc: staticFile("anime/girl-older-than-age/C.C..jfif"),
  // },
  // {
  //   title: "Shinobu Oshino",
  //   description: "598",
  //   subTitle: "Monogatari",
  //   imageSrc: staticFile("anime/girl-older-than-age/Shinobu Oshino.jfif"),
  //   objectPosition: { x: 0, y: 50 },
  // },
  // {
  //   title: "Holo",
  //   description: "600+",
  //   subTitle: "Spice and Wolf",
  //   imageSrc: staticFile("anime/girl-older-than-age/Holo.jfif"),
  //   objectPosition: { x: 0, y: 130 },
  // },
  // {
  //   title: "Leen",
  //   description: "600+",
  //   subTitle: "In Another World With My Smartphone",
  //   imageSrc: staticFile("anime/girl-older-than-age/Leen.jfif"),
  // },
  // {
  //   title: "Mjurran",
  //   description: "700+",
  //   subTitle: "Tensura",
  //   imageSrc: staticFile("anime/girl-older-than-age/Mjurran.jfif"),
  // },
  // {
  //   title: "Senko",
  //   description: "800",
  //   subTitle: "The Helpful Fox Senko-san",
  //   imageSrc: staticFile("anime/girl-older-than-age/Senko.jfif"),
  // },
  // {
  //   title: "Rory Mercury",
  //   description: "967",
  //   subTitle: "Gate",
  //   imageSrc: staticFile("anime/girl-older-than-age/Rury Mercury.jfif"),
  // },
  // {
  //   title: "Frieren",
  //   description: "1000+",
  //   subTitle: "Frieren: Beyond Journey's End",
  //   imageSrc: staticFile("anime/girl-older-than-age/Frieren.jfif"),
  //   objectPosition: { x: 0, y: 135 },
  // },
  // {
  //   title: "Krul Tepes",
  //   description: "1200+",
  //   subTitle: "Seraph of the End",
  //   imageSrc: staticFile("anime/girl-older-than-age/Krul Tepes.jfif"),
  // },
  // {
  //   title: "High Elf Archer",
  //   description: "2000+",
  //   subTitle: "Goblin Slayer",
  //   imageSrc: staticFile("anime/girl-older-than-age/High Elf archer.jfif"),
  // },
  // {
  //   title: "Milim Nava",
  //   description: "2000+",
  //   subTitle: "Tensura",
  //   imageSrc: staticFile("anime/girl-older-than-age/Milim Nava.jfif"),
  // },
  // {
  //   title: "Merlin",
  //   description: "3000+",
  //   subTitle: "Seven Deadly Sins",
  //   imageSrc: staticFile("anime/girl-older-than-age/Merlin.jfif"),
  // },
  // {
  //   title: "Shiroyasha",
  //   description: "5000+",
  //   subTitle: "Mondaiji",
  //   imageSrc: staticFile("anime/girl-older-than-age/Shiroyasha.jfif"),
  // },
  // // {
  // //   title: "Erika Ainsworth",
  // //   description: "6000+",
  // //   subTitle: "Fate",
  // //   imageSrc: "",
  // // },
  // {
  //   title: "Jibril",
  //   description: "6407",
  //   subTitle: "No Game No Life",
  //   imageSrc: staticFile("anime/girl-older-than-age/Jibril.jfif"),
  // },
  // {
  //   title: "Kishirika Kishirisu",
  //   description: "7000+",
  //   subTitle: "Mushoku Tensei",
  //   imageSrc: staticFile("anime/girl-older-than-age/Kishirika kishirisu.jfif"),
  // },
  // {
  //   title: "Azriel",
  //   description: "26000",
  //   subTitle: "No Game No Life",
  //   imageSrc: staticFile("anime/girl-older-than-age/Azriel.jfif"),
  // },
  // {
  //   title: "Militia",
  //   description: "700M+",
  //   subTitle: "The Misfit of Demon King Academy",
  //   imageSrc: staticFile("anime/girl-older-than-age/militia.jfif"),
  // },
  // {
  //   title: "Mitama",
  //   description: "10 Billion",
  //   subTitle: "KamiKatsu",
  //   imageSrc: staticFile("anime/girl-older-than-age/Mitama.jfif"),
  // },
  // {
  //   title: "Najimi Ajimu",
  //   description: "3 Trillion",
  //   subTitle: "Medaka Box",
  //   imageSrc: staticFile("anime/girl-older-than-age/Najimi Ajimu.jfif"),
  //   objectPosition: { x: 0, y: 60 },
  // },
];
