import { staticFile } from "remotion";

const dir = "anime/Kuroko no Basket height";

export const data = [
  {
    title: "Riko Aida",
    description: "156 cm",
    subTitle: "5'1\"",
    imageSrc: staticFile(`${dir}/Riko Aida.jpg`),
  },
  {
    title: "Satsuki Momoi",
    description: "161 cm",
    subTitle: "5'3\"",
    imageSrc: staticFile(`${dir}/Satsuki Momoi.jpg`),
  },
  {
    title: "Tetsuya Kuroko",
    description: "168 cm",
    subTitle: "5'6\"",
    imageSrc: staticFile(`${dir}/Tetsuya Kuroko.jpg`),
  },
  {
    title: "Shinji Koganei",
    description: "170 cm",
    subTitle: "5'7\"",
    imageSrc: staticFile(`${dir}/Shinji Koganei.jpg`),
  },
  // { title: "Koki Furihata", description: "170 cm", subTitle: "5'7\"" },
  {
    title: "Seijuro Akashi",
    description: "173 cm",
    subTitle: "5'8\"",
    imageSrc: staticFile(`${dir}/Seijuro Akashi.jpg`),
  },
  {
    title: "Shun Izuki",
    description: "174 cm",
    subTitle: "5'9\"",
    imageSrc: staticFile(`${dir}/Shun Izuki 1.jpg`),
  },
  {
    title: "Ryo Sakurai",
    description: "175 cm",
    subTitle: "5'9\"",
    imageSrc: staticFile(`${dir}/Sakurai Ryo.jpg`),
  },
  {
    title: "Satoshi Tsuchida",
    description: "176 cm",
    subTitle: "5'9\"",
    imageSrc: staticFile(`${dir}/Satoshi Tsuchida.jpg`),
  },
  {
    title: "Kazunari Takao",
    description: "176 cm",
    subTitle: "5'9\"",
    imageSrc: staticFile(`${dir}/Kazunari Takao.jpg`),
  },
  {
    title: "Junpei Hyuga",
    description: "178 cm",
    subTitle: "5'10\"",
    imageSrc: staticFile(`${dir}/Junpei Hyuga.jpg`),
    objectPosition: {
      x: 3,
      y: -14,
    },
    zoom: 1.13,
  },
  {
    title: "Yukio Kasamatsu",
    description: "178 cm",
    subTitle: "5'10\"",
    imageSrc: staticFile(`${dir}/Yukio Kasamatsu.jpg`),
  },
  {
    title: "Shuzo Nijimura",
    description: "179 cm",
    subTitle: "5'10\"",
    imageSrc: staticFile(`${dir}/Nijimura Shuzo.jpg`),
  },
  {
    title: "Makoto Hanamiya",
    description: "179 cm",
    subTitle: "5'10\"",
    imageSrc: staticFile(`${dir}/Makoto Hanamiya.jpg`),
  },
  {
    title: "Shoichi Imayoshi",
    description: "180 cm",
    subTitle: "5'11\"",
    imageSrc: staticFile(`${dir}/Shoichi Imayoshi.jpg`),
  },
  {
    title: "Kotaro Hayama",
    description: "180 cm",
    subTitle: "5'11\"",
    imageSrc: staticFile(`${dir}/Kotaro Hayama.jpg`),
  },
  {
    title: "Yoshitaka Moriyama",
    description: "181 cm",
    subTitle: "5'11\"",
    imageSrc: staticFile(`${dir}/Moriyama Yoshitaka.jpg`),
  },
  {
    title: "Chihiro Mayuzumi",
    description: "182 cm",
    subTitle: "6'0\"",
    imageSrc: staticFile(`${dir}/Chihiro Mayuzumi.jpg`),
  },
  {
    title: "Tatsuya Himuro",
    description: "183 cm",
    subTitle: "6'0\"",
    imageSrc: staticFile(`${dir}/Himuro Tatsuya.jpg`),
  },
  {
    title: "Mitsuhiro Hayakawa",
    description: "185 cm",
    subTitle: "6'1\"",
    imageSrc: staticFile(`${dir}/Hayakawa Mitsuhiro.jpg`),
  },
  {
    title: "Rinnosuke Mitobe",
    description: "186 cm",
    subTitle: "6'1\"",
    imageSrc: staticFile(`${dir}/Rinnosuke Mitobe.jpg`),
  },
  {
    title: "Reo Mibuchi",
    description: "188 cm",
    subTitle: "6'2\"",
    imageSrc: staticFile(`${dir}/Reo Mibuchi.jpg`),
  },
  {
    title: "Shogo Haizaki",
    description: "188 cm",
    subTitle: "6'2\"",
    imageSrc: staticFile(`${dir}/Shogo Haizaki.jpg`),
  },
  {
    title: "Ryota Kise",
    description: "189 cm",
    subTitle: "6'2\"",
    imageSrc: staticFile(`${dir}/Ryota Kise.jpg`),
  },
  {
    title: "Taiga Kagami",
    description: "190 cm",
    subTitle: "6'3\"",
    imageSrc: staticFile(`${dir}/Taiga Kagami.jpg`),
  },
  {
    title: "Shinsuke Kimura",
    description: "190 cm",
    subTitle: "6'3\"",
    imageSrc: staticFile(`${dir}/Shinsuke Kimura.jpg`),
  },
  {
    title: "Yoshinori Susa",
    description: "190 cm",
    subTitle: "6'3\"",
    imageSrc: staticFile(`${dir}/Yoshinori Susa.jpg`),
  },
  {
    title: "Eikichi Nebuya",
    description: "190 cm",
    subTitle: "6'3\"",
    imageSrc: staticFile(`${dir}/Eikichi Nebuya.jpg`),
  },
  {
    title: "Nash Gold Jr.",
    description: "190 cm",
    subTitle: "6'3\"",
    imageSrc: staticFile(`${dir}/Nash Gold Jr..jpg`),
  },
  {
    title: "Kiyoshi Miyaji",
    description: "191 cm",
    subTitle: "6'3\"",
    imageSrc: staticFile(`${dir}/Miyaji Kiyoshi.jpg`),
  },
  {
    title: "Daiki Aomine",
    description: "192 cm",
    subTitle: "6'4\"",
    imageSrc: staticFile(`${dir}/Daiki Aomine.jpg`),
  },
  {
    title: "Teppei Kiyoshi",
    description: "193 cm",
    subTitle: "6'4\"",
    imageSrc: staticFile(`${dir}/Teppei Kiyoshi.jpg`),
  },
  {
    title: "Kosuke Wakamatsu",
    description: "193 cm",
    subTitle: "6'4\"",
    imageSrc: staticFile(`${dir}/Wakamatsu Kosuke.jpg`),
  },
  {
    title: "Shintaro Midorima",
    description: "195 cm",
    subTitle: "6'5\"",
    imageSrc: staticFile(`${dir}/Shintaro Midorima.jpg`),
  },
  {
    title: "Taisuke Otsubo",
    description: "198 cm",
    subTitle: "6'6\"",
    imageSrc: staticFile(`${dir}/Taisuke Otsubo.jpg`),
  },
  {
    title: "Kenichi Okamura",
    description: "200 cm",
    subTitle: "6'7\"",
    imageSrc: staticFile(`${dir}/Okamura Kenichi.jpg`),
  },
  // { title: "Papa Mbaye Siki", description: "200 cm", subTitle: "6'7\"", imageSrc: staticFile(`${dir}/Papa Mbaye Siki _ Anime - Kuroko's Basketball _ Birthday - June 6.jpg`) },
  {
    title: "Wei Liu",
    description: "203 cm",
    subTitle: "6'8\"",
    imageSrc: staticFile(`${dir}/Wei Liu.jpg`),

    objectPosition: {
      x: 10,
      y: -17,
    },
    zoom: 1.25,
  },
  {
    title: "Atsushi Murasakibara",
    description: "208 cm",
    subTitle: "6'10\"",
    imageSrc: staticFile(`${dir}/Atsushi Murasakibara.jpg`),
  },
  {
    title: "Jason Silver",
    description: "210 cm",
    subTitle: "6'11\"",
    imageSrc: staticFile(`${dir}/Jason Silver.jpg`),
    zoom: 1.1,
  },
];
