import { staticFile } from "remotion";

export const data = [
  {
    topTitle: "Kuro",
    topImageSrc: staticFile("anime/right-hand-one-piece/Kuro.jpg"),
    bottomTitle: "Jango",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Jango.jpg"),
  },
  {
    topTitle: "Don Krieg",
    topImageSrc: staticFile("anime/right-hand-one-piece/Krieg.jpg"),
    bottomTitle: "Gin",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Gin.jpg"),
  },
  {
    topTitle: "Buggy",
    topImageSrc: staticFile("anime/right-hand-one-piece/Buggy.jpg"),
    bottomTitle: "Alvida",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Alvida.jpg"),
  },
  {
    topTitle: "Smoker",
    topImageSrc: staticFile("anime/right-hand-one-piece/smoker.jpg"),
    bottomTitle: "Tashigi",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/tashigi.jpg"),
  },
  {
    topTitle: "Crocodile",
    topImageSrc: staticFile("anime/right-hand-one-piece/Crocodile.jpg"),
    bottomTitle: "Mr.1",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Mr1.png"),
  },
  {
    topTitle: "Enel",
    topImageSrc: staticFile("anime/right-hand-one-piece/Enel.jpg"),
    bottomTitle: "Ohm",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Ohm.jpg"),
  },
  {
    topTitle: "Lucci",
    topImageSrc: staticFile("anime/right-hand-one-piece/Lucci.jpg"),
    bottomTitle: "Kaku",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Kaku.jpg"),
  },
  {
    topTitle: "Gecko Moria",
    topImageSrc: staticFile("anime/right-hand-one-piece/Moria.jpg"),
    bottomTitle: "Dr. Hogback",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Hogback.jpg"),
  },
  {
    topTitle: "Eustass Kid",
    topImageSrc: staticFile("anime/right-hand-one-piece/eustass kid.jpg"),
    bottomTitle: "Killer",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/killer.jpg"),
  },
  {
    topTitle: "Trafalgar Law",
    topImageSrc: staticFile("anime/right-hand-one-piece/trafalgar law.jpg"),
    bottomTitle: "Bepo",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Bepo.jpg"),
  },
  {
    topTitle: "Basil Hawkins",
    topImageSrc: staticFile("anime/right-hand-one-piece/Hawkins.jpg"),
    bottomTitle: "Faust",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Faust.webp"),
    bottomObjectPosition: {
      x: 0,
      y: 176,
    },
  },
  {
    topTitle: "X Drake",
    topImageSrc: staticFile("anime/right-hand-one-piece/X Drake.jpg"),
    bottomTitle: "Solitiar",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Solitiar.webp"),
  },
  {
    topTitle: "Boa Hancock",
    topImageSrc: staticFile("anime/right-hand-one-piece/Hancock.jpg"),
    bottomTitle: "Boa Sandersonia & Boa Marigold",
    bottomImageSrc: staticFile(
      "anime/right-hand-one-piece/Sandersonia & boa marigold.jpg",
    ),
  },
  {
    topTitle: "Magellan",
    topImageSrc: staticFile("anime/right-hand-one-piece/Magellan.jpg"),
    bottomTitle: "Hannyabal",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Hannyabal.jpg"),
  },
  {
    topTitle: "Garp",
    topImageSrc: staticFile("anime/right-hand-one-piece/Garp.jpg"),
    bottomTitle: "Bogard",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Bogard.webp"),
  },
  {
    topTitle: "Fisher Tiger",
    topImageSrc: staticFile("anime/right-hand-one-piece/Fisher Tiger.jpg"),
    bottomTitle: "Jinbe",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Jinbe.jpg"),
  },
  {
    topTitle: "Hody Jones",
    topImageSrc: staticFile("anime/right-hand-one-piece/Hody Jones.jpg"),
    bottomTitle: "Dosun",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Dosun.webp"),
  },
  {
    topTitle: "Caesar",
    topImageSrc: staticFile("anime/right-hand-one-piece/Caesar.jpg"),
    bottomTitle: "Monet",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Monet.jpg"),
  },
  {
    topTitle: "Donquixote Doflamingo",
    topImageSrc: staticFile("anime/right-hand-one-piece/Doflamingo.jpg"),
    bottomTitle: "Trebol",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Trebol.jpg"),
  },
  {
    topTitle: "Kyros",
    topImageSrc: staticFile("anime/right-hand-one-piece/Kyros.jpg"),
    bottomTitle: "Rebecca",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Rebecca.jpg"),
  },
  {
    topTitle: "Kurozumi Orochi",
    topImageSrc: staticFile("anime/right-hand-one-piece/Kurozumi Orochi.jpg"),
    bottomTitle: "Denjiro",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Denjiro.jpg"),
  },
  {
    topTitle: "Vegapunk",
    topImageSrc: staticFile("anime/right-hand-one-piece/Vegapunk.jpg"),
    bottomTitle: "Sentomaru",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/sentomaru.jpg"),
  },
  {
    topTitle: "Big Mom",
    topImageSrc: staticFile("anime/right-hand-one-piece/Big Mom.jpg"),
    bottomTitle: "Charlotte Katakuri",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Katakuri.jpg"),
  },
  {
    topTitle: "Kaido",
    topImageSrc: staticFile("anime/right-hand-one-piece/Kaido.jpg"),
    bottomTitle: "King",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/king.avif"),
  },
  {
    topTitle: "Blackbeard",
    topImageSrc: staticFile("anime/right-hand-one-piece/Blackbeard.jpg"),
    bottomTitle: "Shiryu",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Shiryu.jpg"),
  },
  {
    topTitle: "Monkey D. Dragon",
    topImageSrc: staticFile("anime/right-hand-one-piece/Dragon.jpg"),
    bottomTitle: "Sabo",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Sabo.jpg"),
  },
  {
    topTitle: "Whitebeard",
    topImageSrc: staticFile("anime/right-hand-one-piece/Whitebeard.jpg"),
    bottomTitle: "Marco",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Marco.jpg"),
  },
  {
    topTitle: "Shanks",
    topImageSrc: staticFile("anime/right-hand-one-piece/Shanks.jpg"),
    bottomTitle: "Benn Beckman",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Benn Beckman.jpg"),
  },
  {
    topTitle: "Gol D. Roger",
    topImageSrc: staticFile("anime/right-hand-one-piece/Roger.jpg"),
    bottomTitle: "Rayleigh",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Rayleigh.jpg"),
  },
  {
    topTitle: "Monkey D. Luffy",
    topImageSrc: staticFile("anime/right-hand-one-piece/Luffy.jpg"),
    bottomTitle: "Roronoa Zoro",
    bottomImageSrc: staticFile("anime/right-hand-one-piece/Roronoa Zoro.jpg"),
  },
];
