import { staticFile } from "remotion";

const op = (file: string) => staticFile(`anime/onepiece/${file}`);

export const data = [
  { title: "Tama", description: "8", imageSrc: op("Tama.jpg") },
  { title: "Momonosuke", description: "8", imageSrc: op("Momonosuke.jfif") },
  { title: "Chopper", description: "17", imageSrc: op("Chopper.jfif") },
  { title: "Luffy", description: "19", imageSrc: op("Luffy.jfif") },
  { title: "Usopp", description: "19", imageSrc: op("Usopp.jfif") },
  { title: "Nami", description: "20", imageSrc: op("Nami.jfif") },
  { title: "Sanji", description: "21", imageSrc: op("Sanji.jfif") },
  { title: "Zoro", description: "21", imageSrc: op("Zoro.jfif") },
  { title: "Law", description: "26", imageSrc: op("Trafalgar Law.jpg") },
  { title: "Yamato", description: "28", imageSrc: op("Yamato.jfif") },
  { title: "Robin", description: "30", imageSrc: op("Robin.jfif") },
  { title: "Hancock", description: "31", imageSrc: op("Hancock.jpg") },
  { title: "Shanks", description: "39", imageSrc: op("Shanks.jpg") },
  { title: "Blackbeard", description: "40", imageSrc: op("Blackbeard.jpg") },
  { title: "Mihawk", description: "43", imageSrc: op("Mihawk.jpg") },
  { title: "Crocodile", description: "46", imageSrc: op("Crocodile.jpg") },
  { title: "Jinbe", description: "46", imageSrc: op("Jinbe.jpg") },
  { title: "Aokiji", description: "49", imageSrc: op("Aokiji.jpg") },
  { title: "Akainu", description: "55", imageSrc: op("Akainu.jpg") },
  { title: "Kizaru", description: "58", imageSrc: op("Kizaru.jpg") },
  { title: "Kaido", description: "59", imageSrc: op("Kaido.jpg") },
  { title: "Shakky", description: "64", imageSrc: op("Shakky.jpg") },
  { title: "Vegapunk", description: "65", imageSrc: op("Vegapunk.jpg") },
  { title: "Big Mom", description: "68", imageSrc: op("Big Mom.jfif") },
  { title: "Whitebeard", description: "72", imageSrc: op("Whitebeard.jpg") },
  { title: "Tsuru", description: "76", imageSrc: op("Tsuru.jpg") },
  { title: "Garp", description: "78", imageSrc: op("Garp.jpg") },
  {
    title: "Rayleigh",
    description: "78",
    imageSrc: op("Rayleigh.jpg"),
  },
  { title: "Sengoku", description: "79", imageSrc: op("Sengoku.jpg") },
  { title: "Brook", description: "90", imageSrc: op("Brook.jfif") },
  {
    title: "Dr. Kureha",
    description: "141",
    imageSrc: op("Dr. Kureha.jpg"),
  },
  {
    title: "Dorry",
    description: "160",
    imageSrc: op("Dorry.jpg"),
  },
  {
    title: "Broggy",
    description: "164",
    imageSrc: op("Broggy.jpg"),
  },
  {
    title: "Jarul",
    description: "345",
    imageSrc: op("Jarul.jpg"),
  },
  {
    title: "The Gorosei",
    description: "800+",
    imageSrc: op("Gorosei.jpg"),
  },
  { title: "Imu", description: "800+", imageSrc: op("Imu.jpg") },
  {
    title: "Joy Boy",
    description: "800+",
    imageSrc: op("Joy Boy.jpg"),
  },
  {
    title: "Zunesha",
    description: "1000+",
    imageSrc: op("Zunesha.jpg"),
  },
];
