import { staticFile } from "remotion";

export const data = [
  {
    topTitle: "Edward Newgate",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Whitebeard Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Bartolomeo",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Barto Club",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Brook",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Rumbar Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Xebec",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Rocks Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Buggy",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Buggy Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Kaido",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Beast Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Fake Luffy",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Fake Straw Hat Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Trafalgar Law",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Heart Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Boa Hancock",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Kuja Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Gol D. Roger",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Roger Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Fisher Tiger",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Sun Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Hody Jones",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "New Fishman Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Usopp",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Usopp Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Kuro",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Black Cat Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Luffy",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Straw Hat Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Shiki",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Golden Lion Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Charlotte Linlin",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Big Mom Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Marshall D. Teach",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Blackbeard Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Arlong",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Arlong Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Crocodile",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Baroque Works",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Monkey D. Dragon",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Revolutionary Army",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Bellamy",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Bellamy Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Portgas D. Ace",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Spade Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Doflamingo",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Donquixote Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Eustass Kid",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Kid Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Gecko Moria",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Thriller Bark Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Foxy",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Foxy Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Jewerly Bonney",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Bonney Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Shanks",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Red Hair Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Basil Hawkins",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Hawkins Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Leo",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Tontatta Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Krieg",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Krieg Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Apoo",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "On Air Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Capone Bege",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Fire Tank Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Wapol",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Bliking Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Urouge",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Fallen Monk Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "X Drake",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Drake Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Cavendish",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Beautiful Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Alvida",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Alvida Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Chadros Higelyges",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Brownbeard Pirates",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
  {
    topTitle: "Crocodile & Mihawk",
    topImageSrc: staticFile("anime/onepiece-pirate-captain/Luffy.jpg"),
    bottomTitle: "Cross Guild",
    bottomImageSrc: staticFile("anime/onepiece-pirate-captain/Zoro.jpg"),
  },
];
